### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by asjeb** [DassHydro/smash#236]
After fetch and pull main with update env.
make edit ok but not make :

>>> import smash 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aelbaz/Bureau/smash-main/smash/__init__.py", line 1, in <module>
    from smash import factory, io
  File "/home/aelbaz/Bureau/smash-main/smash/factory/__init__.py", line 1, in <module>
    from smash.factory.dataset.dataset import load_dataset
  File "/home/aelbaz/Bureau/smash-main/smash/factory/dataset/dataset.py", line 6, in <module>
    from smash.io.mesh import read_mesh
  File "/home/aelbaz/Bureau/smash-main/smash/io/__init__.py", line 1, in <module>
    from smash.io.mesh import read_mesh, save_mesh
  File "/home/aelbaz/Bureau/smash-main/smash/io/mesh.py", line 10, in <module>
    from smash.io.handler._hdf5_handler import _dump_dict, _load_hdf5_to_dict
  File "/home/aelbaz/Bureau/smash-main/smash/io/handler/_hdf5_handler.py", line 9, in <module>
    from smash.fcore._mwd_sparse_matrix import Sparse_MatrixDT
ModuleNotFoundError: No module named 'smash.fcore._mwd_sparse_matrix'

**Comment by nghi-truyen** [comment]
On a vu ce problème avec François, il faudrait juste que tu lance ton script ou ton console Python dans un autre répertoire qui contient pas un dossier qui s'appelle smash.

**Comment by asjeb** [comment]
Sinon link vers la version du git
