### ISSUE TITLE
Support needed for numpy > 2.1 (october 2024)

### ISSUE THREAD

**Issue by maximejay** [DassHydro/smash#341]
#Description  
Affect  smash-1.1.0rc1. Current developer install with pip failed with the latest version of numpy (2.1.2 october 2024). Import smash will failed.

#Log  

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/spyder_kernels/console/__main__.py", line 24, in <module>
    start.main()
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/spyder_kernels/console/start.py", line 207, in main
    kernel.start()
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/spyder_kernels/console/shell.py", line 364, in run_code
    return await super().run_code(*args, **kwargs)
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_60544/1770147163.py", line 1, in <module>
    import smash
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/smash/__init__.py", line 1, in <module>
    from smash import factory, io
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/smash/factory/__init__.py", line 2, in <module>
    from smash.factory.mesh.mesh import detect_sink, generate_mesh
  File "/home/maxime/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/smash/factory/mesh/mesh.py", line 10, in <module>
    from smash.factory.mesh._libmesh import mw_mesh
AttributeError: _ARRAY_API not found

Traceback (most recent call last):

  Cell In[1], line 1
    import smash

  File ~/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/smash/__init__.py:1
    from smash import factory, io

  File ~/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/smash/factory/__init__.py:2
    from smash.factory.mesh.mesh import detect_sink, generate_mesh

  File ~/ACTIONS_ASSIMILATION/2024/venv_assim/lib/python3.10/site-packages/smash/factory/mesh/mesh.py:10
    from smash.factory.mesh._libmesh import mw_mesh

ImportError: numpy.core.multiarray failed to import

#step to reproduce the pb:  

python -m venv env_smash  
source env_smash/bin/activate  
pip install -r requirement_dev.txt  
make  

Then open a python console and try to import smash.  

#Workaround  

pip install --upgrade 'numpy<2.1'
make clean
make

import smash will work as expected.

**Comment by maximejay** [comment]
Cleaning the repository fix the problem, i.e delete your local copy of smash and do a git clone again...
